version: "3"

services:
  rtsp-to-webrtc:
    container_name: rtsp-to-webrtc
    build: 
      context: .
    restart: unless-stopped

    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./config.json:/go/src/app/config.json

    networks:
      vlan_net:
        ipv4_address: 192.168.1.2

networks:
  vlan_net:
    name: vlan_net
    driver: macvlan
    driver_opts:
      parent: eth0
      macvlan_mode: bridge
    ipam:
      driver: default
      config:
        - subnet:  192.168.1.0/24
          gateway:  192.168.1.1
   